---
apiVersion: v1
kind: Pod
metadata:
  name: log-generator
  labels:
    app: log-generator
spec:
  containers:
    - name: log-generator
      image: busybox
      command: ["/bin/sh", "-c", "while true; do echo 'Hello from log-generator'; sleep 5; done"]
